name: timemastermobile_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.0
  path_provider: ^2.0.11 # For accessing the device's file system
  open_file: ^3.3.1      # For opening the downloaded file
  permission_handler: ^10.0.0 



cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Correct asset configuration
  assets:
    - images/logos/
    - images/covers/
    - images/graphic-icons/
    - images/Login/
    - images/SignUp/
    - images/checkEmail/
    - images/persons/
    
